AppBundle\Entity\Access:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AccessRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: integer
    manyToOne:
        role:
            targetEntity: AppBundle\Entity\Role
            inversedBy: accesses
    manyToMany:
        projects:
            targetEntity: AppBundle\Entity\Project
            inversedBy: access
    lifecycleCallbacks: {  }
