AppBundle\Entity\Project:
    type: entity
    table: null
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
        preUpdate: [setUpdatedAtValue]
    repositoryClass: AppBundle\Repository\ProjectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        content:
            type: text
            length: 2047
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
    manyToMany:
        access:
            targetEntity: AppBundle\Entity\Access
            mappedBy: projects
    lifecycleCallbacks: {  }
